### ISSUE TITLE
downgrade required python version

### ISSUE THREAD

**Issue by DaanMeijer** [xrnl/rebel_backup#2]
When installing, pip complains:

> rebel-management-utilities requires Python '>=3.6' but the running Python is 2.7.13

Please adjust the minimum requirements to allow for python3.5 :)

**Comment by SamLubbers** [comment]
@DaanMeijer could you confirm which Python version you require?

You mentioned allowing for Python 3.5 but the running Python is 2.7. Which version do you need?

**Comment by DaanMeijer** [comment]
If you can make it work on python 2.7 that's even better :) I can install up to python 3.5

**Comment by Daksol** [comment]
This is John from the Hague, @john_itdh,
I would prefer if we could settle on Python 3.x.
Ubuntu 18.04 comes with Python 3.7 out of box.
Idle Python for Win10 has Python 3.8.
Thanks.
